# -*- coding: utf-8 -*-
"""MPtensorboard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rxweL_HjqvDBqxZmh9WSX-2fIC4Au0X3
"""

import plotly.express as px
import pandas as pd
import io
from google.colab import files

uploaded = files.upload()

df = pd.read_csv(io.BytesIO(uploaded['MPSRGAN-log.csv']), sep=';', index_col='step')

fig = px.line(df, title='Discriminator losses')
fig.add_scatter(x=df.index, y=df['d_loss_r'], mode='lines', name='Tr Discriminator loss (real)')
fig.add_scatter(x=df.index, y=df['d_loss_f'], mode='lines', name='Tr Discriminator loss (fake)')
fig.add_scatter(x=df.index, y=df['val_d_loss_r'], mode='lines', name='Va Discriminator loss (real)')
fig.add_scatter(x=df.index, y=df['val_d_loss_f'], mode='lines', name='Va Discriminator loss (fake)')
fig.show()

fig = px.line(df, title='Generator losses (Discriminator)')
fig.add_scatter(x=df.index, y=df['g_loss_d'], mode='lines', name='Train')
fig.add_scatter(x=df.index, y=df['val_g_loss_d'], mode='lines', name='Validation')
fig.show()

fig = px.line(df, title='Generator losses (VGG19)')
fig.add_scatter(x=df.index, y=df['g_loss_vgg'], mode='lines', name='Train')
fig.add_scatter(x=df.index, y=df['val_g_loss_vgg'], mode='lines', name='Validation')
fig.show()
